# Generated by Django 4.2.7 on 2023-11-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('username', models.CharField(default='', max_length=50, verbose_name='Username')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='Email')),
                ('password', models.CharField(default='', max_length=50, verbose_name='Password')),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='profilepic')),
            ],
        ),
    ]
