# Generated by Django 4.2.7 on 2023-11-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0002_rename_admin_adminpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminPage',
            new_name='Teachers',
        ),
    ]
