# Generated by Django 4.2.7 on 2023-11-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0003_rename_adminpage_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
