# Generated by Django 4.2.7 on 2023-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0004_rename_teachers_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Lesson Name')),
                ('info', models.TextField(verbose_name='Lesson Info')),
                ('example', models.TextField(verbose_name='Lesson Example')),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='medialesson/', verbose_name='multimedia')),
                ('file', models.FileField(blank=True, null=True, upload_to='mediafiles/', verbose_name='file')),
            ],
        ),
    ]
