# Generated by Django 4.2.7 on 2023-11-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0005_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=255, verbose_name='Lesson Name')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=255, verbose_name='Lesson Name')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
    ]
