# Generated by Django 4.2.7 on 2023-12-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0006_assessmentquestion_quizquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='example',
        ),
        migrations.AddField(
            model_name='lesson',
            name='exercise',
            field=models.TextField(null=True, verbose_name='Lesson Exercise'),
        ),
    ]
