# Generated by Django 4.2.7 on 2023-12-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0008_alter_lesson_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='report'),
        ),
    ]
