# Generated by Django 4.2.7 on 2023-12-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='lesson',
            field=models.CharField(default='', max_length=50, verbose_name='Lesson'),
        ),
    ]
