# Generated by Django 4.2.7 on 2023-11-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0002_student_email_student_password_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_no',
        ),
    ]
