# Generated by Django 4.2.7 on 2023-11-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0003_remove_student_stud_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
