# Generated by Django 4.2.7 on 2023-12-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0005_user_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images/certificates/', verbose_name='certificate'),
        ),
    ]
